## Problema 1

#### Usando os dados da Tabela 2.1, Capítulo 2:

In [1]:
import pandas as pd
import statistics as stat
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('C:\Estatística Básica\Conjunto de Dados.xls', sheet_name='Tabela 2.1', header=0)
df

,N,Estado Civil,Grau de Instrução,N de Filhos,Salario (x Sal Min),Idade - Anos,Idade - Meses,Região de Procedência
0,1,solteiro,ensino fundamental,NaN,4.00,26,3,interior
1,2,casado,ensino fundamental,1.0,4.56,32,10,capital
2,3,casado,ensino fundamental,2.0,5.25,36,5,capital
3,4,solteiro,ensino médio,NaN,5.73,20,10,outra
4,5,solteiro,ensino fundamental,NaN,6.26,40,7,outra
5,6,casado,ensino fundamental,0.0,6.66,28,0,interior
6,7,solteiro,ensino fundamental,NaN,6.86,41,0,interior
7,8,solteiro,ensino fundamental,NaN,7.39,43,4,capital
8,9,casado,ensino médio,1.0,7.59,34,10,capital
9,10,solteiro,ensino médio,NaN,7.44,23,6,outra
10,11,casado,ensino médio,2.0,8.12,33,6,interior
11,12,solteiro,ensino fundamental,NaN,8.46,27,11,capital
12,13,solteiro,ensino médio,NaN,8.74,37,5,outra
13,14,casado,ensino fundamental,3.0,8.95,44,2,outra
14,15,casado,ensino médio,0.0,9.13,30,5,interior
15,16,solteiro,ensino médio,NaN,9.35,38,8,outra
16,17,casado,ensino médio,1.0,9.77,31,7,capital
17,18,casado,ensino fundamental,2.0,9.80,39,7,outra
18,19,solteiro,superior,NaN,10.53,25,8,interior
19,20,solteiro,ensino médio,NaN,10.76,37,4,interior
20,21,casado,ensino médio,1.0,11.06,30,9,outra
21,22,solteiro,ensino médio,NaN,11.59,34,2,capital
22,23,solteiro,ensino fundamental,NaN,12.00,41,0,outra
23,24,casado,superior,0.0,12.79,26,1,outra
24,25,casado,ensino médio,2.0,13.23,32,5,interior
25,26,casado,ensino médio,2.0,13.60,35,0,outra
26,27,solteiro,ensino fundamental,NaN,13.85,46,7,outra
27,28,casado,ensino médio,0.0,14.69,29,8,interior
28,29,casado,ensino médio,5.0,14.71,40,6,interior
29,30,casado,ensino médio,2.0,15.99,35,10,capital
30,31,solteiro,superior,NaN,16.22,31,5,outra
31,32,casado,ensino médio,1.0,16.61,36,4,interior
32,33,casado,superior,3.0,17.26,43,7,capital
33,34,solteiro,superior,NaN,18.75,33,7,capital
34,35,casado,ensino médio,2.0,19.40,48,11,capital
35,36,casado,superior,3.0,23.30,42,2,interior

##### (a) Construa a distribuição de frequência conjunta para as variáveis Grau de Instrução e Região de Procedência.

In [3]:
frequencias_conjuntas = {}
frequencias_conjuntas['Fundamental*Capital']=0
frequencias_conjuntas['Fundamental*Interior']=0
frequencias_conjuntas['Fundamental*Outra']=0
frequencias_conjuntas['Médio*Capital']=0
frequencias_conjuntas['Médio*Interior']=0
frequencias_conjuntas['Médio*Outra']=0
frequencias_conjuntas['Superior*Capital']=0
frequencias_conjuntas['Superior*Interior']=0
frequencias_conjuntas['Superior*Outra']=0

for index, row in df.iterrows():
    if row['Grau de Instrução']=='ensino fundamental':
        if row['Região de Procedência']=='capital':
            frequencias_conjuntas['Fundamental*Capital']+=1
        if row['Região de Procedência']=='interior':
            frequencias_conjuntas['Fundamental*Interior']+=1
        if row['Região de Procedência']=='outra':
            frequencias_conjuntas['Fundamental*Outra']+=1
    if row['Grau de Instrução']=='ensino médio':
        if row['Região de Procedência']=='capital':
            frequencias_conjuntas['Médio*Capital']+=1
        if row['Região de Procedência']=='interior':
            frequencias_conjuntas['Médio*Interior']+=1
        if row['Região de Procedência']=='outra':
            frequencias_conjuntas['Médio*Outra']+=1
    if row['Grau de Instrução']=='superior':
        if row['Região de Procedência']=='capital':
            frequencias_conjuntas['Superior*Capital']+=1
        if row['Região de Procedência']=='interior':
            frequencias_conjuntas['Superior*Interior']+=1
        if row['Região de Procedência']=='outra':
            frequencias_conjuntas['Superior*Outra']+=1

df_frequencia_conjunta=pd.DataFrame(
    data={
        "Fundamental":[frequencias_conjuntas['Fundamental*Capital'],
                       frequencias_conjuntas['Fundamental*Interior'],
                       frequencias_conjuntas['Fundamental*Outra'],
                       frequencias_conjuntas['Fundamental*Capital']+frequencias_conjuntas['Fundamental*Interior']+frequencias_conjuntas['Fundamental*Outra']
                      ],
        "Médio":[frequencias_conjuntas['Médio*Capital'],
                 frequencias_conjuntas['Médio*Interior'],
                 frequencias_conjuntas['Médio*Outra'],
                 frequencias_conjuntas['Médio*Capital']+frequencias_conjuntas['Médio*Interior']+frequencias_conjuntas['Médio*Outra']
                ],
        "Superior":[frequencias_conjuntas['Superior*Capital'],
                    frequencias_conjuntas['Superior*Interior'],
                    frequencias_conjuntas['Superior*Outra'],
                    frequencias_conjuntas['Superior*Capital']+frequencias_conjuntas['Superior*Interior']+frequencias_conjuntas['Superior*Outra']
                ],
        "Total":[frequencias_conjuntas['Fundamental*Capital']+frequencias_conjuntas['Médio*Capital']+frequencias_conjuntas['Superior*Capital'],
                 frequencias_conjuntas['Fundamental*Interior']+frequencias_conjuntas['Médio*Interior']+frequencias_conjuntas['Superior*Interior'],
                 frequencias_conjuntas['Fundamental*Outra']+frequencias_conjuntas['Médio*Outra']+frequencias_conjuntas['Superior*Outra'],
                 len(df)
                ]
    },
    index=['Capital','Interior','Outra','Total']
)
print('Distribuição de frequência conjunta:')
df_frequencia_conjunta

Distribuição de frequência conjunta:

          Fundamental  Médio  Superior  Total
Capital             4      5         2     11
Interior            3      7         2     12
Outra               5      6         2     13
Total              12     18         6     36

##### (b) Qual a porcentagem de funcionários que tem o ensino médio?

In [4]:
porcentagem_ensino_medio= 100 * ( df_frequencia_conjunta.at['Total','Médio'] / df_frequencia_conjunta.at['Total','Total'] )
print('Porcentagem de funcionários que tem somente o ensino médio:', porcentagem_ensino_medio)
porcentagem_ensino_medio_ou_medio_superior= 100 * ( ( df_frequencia_conjunta.at['Total','Médio'] + df_frequencia_conjunta.at['Total','Superior'] ) / df_frequencia_conjunta.at['Total','Total'] )
print('Porcentagem de funcionários que tem o ensino médio ou médio e superior:', porcentagem_ensino_medio_ou_medio_superior)

Porcentagem de funcionários que tem somente o ensino médio: 50.0
Porcentagem de funcionários que tem o ensino médio ou médio e superior: 66.66666666666666

##### (c) Qual a porcentagem daqueles que tem o ensino médio e são do interior?

In [5]:
porcentagem_ensino_medio_interior = 100 * ( df_frequencia_conjunta.at['Interior','Médio'] / df_frequencia_conjunta.at['Total','Total'] )
print('Porcentagem de funcionários que tem somente o ensino médio e são do interior:', porcentagem_ensino_medio_interior)

Porcentagem de funcionários que tem somente o ensino médio e são do interior: 19.444444444444446

##### (d) Dentre os funcionários do interior, quantos porcento tem o ensino médio?

In [6]:
no_interior_ensino_medio = 100 * ( df_frequencia_conjunta.at['Interior','Médio'] / df_frequencia_conjunta.at['Interior','Total'] )
print('No interior, quantos porcento tem ensino médio:', no_interior_ensino_medio)

No interior, quantos porcento tem ensino médio: 58.333333333333336